//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recipies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recipies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Recipies", typeof(Recipies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink margarita pochodzi z Meksyku. Jego nazwa prawdopodobnie wzięła się od imienia kobiety, dla której został przygotowany po raz pierwszy. To pyszny, orzeźwiający napój najczęściej przygotowywany z dodatkiem cytryny. Można go również podawać z innymi owocami lub sokami owocowymi - szczególną popularnością cieszy się wersja truskawkowa. Ważnym elementem podania Margarity jest crustowanie brzegu szklanki, w której podaje się koktajl..
        /// </summary>
        internal static string margharitaDescription {
            get {
                return ResourceManager.GetString("margharitaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml tequili.
        /// </summary>
        internal static string margharitaIngredient1 {
            get {
                return ResourceManager.GetString("margharitaIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml triple sec.
        /// </summary>
        internal static string margharitaIngredient2 {
            get {
                return ResourceManager.GetString("margharitaIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sok z połówki limonki.
        /// </summary>
        internal static string margharitaIngredient3 {
            get {
                return ResourceManager.GetString("margharitaIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 ml syropu cukrowego.
        /// </summary>
        internal static string margharitaIngredient4 {
            get {
                return ResourceManager.GetString("margharitaIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do shakera wlewamy tequile, triple sec, sok z limonki, wrzucamy kostki lodu i shake-ujemy. Zawartość shakera wlewamy do kieliszka koktajlowego. Smacznego!.
        /// </summary>
        internal static string margharitaRecipe {
            get {
                return ResourceManager.GetString("margharitaRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margharita.
        /// </summary>
        internal static string margharitaTitle {
            get {
                return ResourceManager.GetString("margharitaTitle", resourceCulture);
            }
        }
    }
}
