//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recipies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recipies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Recipies", typeof(Recipies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To klasyka dla każdego, kto lubi drinki z wódką i kawą oraz ulubiony koktajl Biga Lebowskiego. Słodki i mocny koktajl dla niecierpliwych, bo przygotowanie jego zajmuje jakieś 12 sekund..
        /// </summary>
        internal static string blackWhiteRussianDescription {
            get {
                return ResourceManager.GetString("blackWhiteRussianDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 ml wódki.
        /// </summary>
        internal static string blackWhiteRussianIngredient1 {
            get {
                return ResourceManager.GetString("blackWhiteRussianIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 ml likieru kawowego.
        /// </summary>
        internal static string blackWhiteRussianIngredient2 {
            get {
                return ResourceManager.GetString("blackWhiteRussianIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 ml śmietanki 30% / mleka (w wariancie White Russian).
        /// </summary>
        internal static string blackWhiteRussianIngredient3 {
            get {
                return ResourceManager.GetString("blackWhiteRussianIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypełnij szklankę typu short w kolejności - wódką, likierem i śmietanką / mlekiem. Gotowe!.
        /// </summary>
        internal static string blackWhiteRussianRecipe {
            get {
                return ResourceManager.GetString("blackWhiteRussianRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black / White Russian.
        /// </summary>
        internal static string blackWhiteRussianTitle {
            get {
                return ResourceManager.GetString("blackWhiteRussianTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmopolitan to drink na każdą okazję, którym możesz się cieszyć i w barze, i w domowym zaciszu. Prosty przepis, elegancki wygląd – oto najlepsza recepta na relaks z koleżankami i filmowym koktajlem..
        /// </summary>
        internal static string cosmopolitanDescription {
            get {
                return ResourceManager.GetString("cosmopolitanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml wódki.
        /// </summary>
        internal static string cosmopolitanIngredient1 {
            get {
                return ResourceManager.GetString("cosmopolitanIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml Triple Sec / Cointreau.
        /// </summary>
        internal static string cosmopolitanIngredient2 {
            get {
                return ResourceManager.GetString("cosmopolitanIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 ml sok żurawinowy.
        /// </summary>
        internal static string cosmopolitanIngredient3 {
            get {
                return ResourceManager.GetString("cosmopolitanIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 ml soku z cytryny.
        /// </summary>
        internal static string cosmopolitanIngredient4 {
            get {
                return ResourceManager.GetString("cosmopolitanIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do shakera wlej wszystkie składniki oraz energicznie wstrząśnij. Przelej poprzez double-strain do schłodzonej koktajlówki..
        /// </summary>
        internal static string cosmopolitanRecipe {
            get {
                return ResourceManager.GetString("cosmopolitanRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmopolitan.
        /// </summary>
        internal static string cosmopolitanTitle {
            get {
                return ResourceManager.GetString("cosmopolitanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string cubaLibreDescription {
            get {
                return ResourceManager.GetString("cubaLibreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml białego rumu.
        /// </summary>
        internal static string cubaLibreIngredient1 {
            get {
                return ResourceManager.GetString("cubaLibreIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100-150 ml Coca-Cola.
        /// </summary>
        internal static string cubaLibreIngredient2 {
            get {
                return ResourceManager.GetString("cubaLibreIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 ćwiartki limonki.
        /// </summary>
        internal static string cubaLibreIngredient3 {
            get {
                return ResourceManager.GetString("cubaLibreIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do szklanki typu long wrzuć cząstki limonki, zgnieć mudlerem. Następnie zasyp szkło kostkami lodu, wlej rum i Coca-Colę..
        /// </summary>
        internal static string cubaLibreRecipe {
            get {
                return ResourceManager.GetString("cubaLibreRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba Libre.
        /// </summary>
        internal static string cubaLibreTitle {
            get {
                return ResourceManager.GetString("cubaLibreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string daiquiriDescription {
            get {
                return ResourceManager.GetString("daiquiriDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml jasnego rumu.
        /// </summary>
        internal static string daiquiriIngredient1 {
            get {
                return ResourceManager.GetString("daiquiriIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml soku z limonki.
        /// </summary>
        internal static string daiquiriIngredient2 {
            get {
                return ResourceManager.GetString("daiquiriIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 ml syropu cukrowego.
        /// </summary>
        internal static string daiquiriIngredient3 {
            get {
                return ResourceManager.GetString("daiquiriIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daiquiri.
        /// </summary>
        internal static string daiquiriTitle {
            get {
                return ResourceManager.GetString("daiquiriTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie składniki wlej do shakera pełnego lodu i energicznie wstrząśnij. Tak przygotowany koktajl przelej poprzez double-strain do schłodzonego kieliszka koktajlowego..
        /// </summary>
        internal static string daqiuiriRecipe {
            get {
                return ResourceManager.GetString("daqiuiriRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espresso Martini jest nazywany przez barmanów współczesnym klasykiem, czyli koktajlem znanym i pitym w barach na całym świecie, bazującym na szeroko dostępnych składnikach z wystandaryzowaną i znaną recepturą. Skomponowany został w latach 90. przez londyńskiego guru barowego Dicka Bradsella, który w dużej części odpowiada za to, co dziś pijamy wieczorową porą..
        /// </summary>
        internal static string espressoMartiniDescription {
            get {
                return ResourceManager.GetString("espressoMartiniDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 ml wódki.
        /// </summary>
        internal static string espressoMartiniIngredient1 {
            get {
                return ResourceManager.GetString("espressoMartiniIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 ml likieru Kahlua.
        /// </summary>
        internal static string espressoMartiniIngredient2 {
            get {
                return ResourceManager.GetString("espressoMartiniIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filiżanka espresso.
        /// </summary>
        internal static string espressoMartiniIngredient3 {
            get {
                return ResourceManager.GetString("espressoMartiniIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 ml syropu cukrowego.
        /// </summary>
        internal static string espressoMartiniIngredient4 {
            get {
                return ResourceManager.GetString("espressoMartiniIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składniki wlej do shakare i energicznie wstrząśnij. Tak przygotowany koktajl przelej do schłodzonego kieliszka koktajlowego poprzez double-strain..
        /// </summary>
        internal static string espressoMartiniRecipe {
            get {
                return ResourceManager.GetString("espressoMartiniRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espresso Martini.
        /// </summary>
        internal static string espressoMartiniTitle {
            get {
                return ResourceManager.GetString("espressoMartiniTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string etr {
            get {
                return ResourceManager.GetString("etr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink Manhattan w dziejach sztuki barmańskiej zapisał się jako pierwszy drink z wermutem oraz wielki poprzednik dwóch innych klasyków: Martineza i Martini. Choć lista drinków z whiskey jest długa, Manhattan zajmuje na niej wyjątkowe miejsce. Dlaczego? Bez niego nie powstałby słynny drink Martini kojarzony z przygodami Jamesa Bonda..
        /// </summary>
        internal static string manhattanDescription {
            get {
                return ResourceManager.GetString("manhattanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 ml bourbon&apos;u.
        /// </summary>
        internal static string manhattanIngredient1 {
            get {
                return ResourceManager.GetString("manhattanIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 ml słodkiego wermutu.
        /// </summary>
        internal static string manhattanIngredient2 {
            get {
                return ResourceManager.GetString("manhattanIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-3 krople Angostury.
        /// </summary>
        internal static string manhattanIngredient3 {
            get {
                return ResourceManager.GetString("manhattanIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie składniki należy wlać do shakera z lodem i energicznie wymieszać. Następnie przelać poprzez double-strain do dobrze schłodzonej koktajlówki..
        /// </summary>
        internal static string manhattanRecipe {
            get {
                return ResourceManager.GetString("manhattanRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manhattan.
        /// </summary>
        internal static string manhattanTitle {
            get {
                return ResourceManager.GetString("manhattanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink margarita pochodzi z Meksyku. Jego nazwa prawdopodobnie wzięła się od imienia kobiety, dla której został przygotowany po raz pierwszy. To pyszny, orzeźwiający napój najczęściej przygotowywany z dodatkiem cytryny. Można go również podawać z innymi owocami lub sokami owocowymi - szczególną popularnością cieszy się wersja truskawkowa. Ważnym elementem podania Margarity jest crustowanie brzegu szklanki, w której podaje się koktajl..
        /// </summary>
        internal static string margharitaDescription {
            get {
                return ResourceManager.GetString("margharitaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml tequili.
        /// </summary>
        internal static string margharitaIngredient1 {
            get {
                return ResourceManager.GetString("margharitaIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml triple sec.
        /// </summary>
        internal static string margharitaIngredient2 {
            get {
                return ResourceManager.GetString("margharitaIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sok z połówki limonki.
        /// </summary>
        internal static string margharitaIngredient3 {
            get {
                return ResourceManager.GetString("margharitaIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 ml syropu cukrowego.
        /// </summary>
        internal static string margharitaIngredient4 {
            get {
                return ResourceManager.GetString("margharitaIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do shakera wlej tequile, triple sec, sok z limonki i syrop cukrowy. Zawartość shakera przelej do schłodzonego kieliszka koktajlowego..
        /// </summary>
        internal static string margharitaRecipe {
            get {
                return ResourceManager.GetString("margharitaRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margharita.
        /// </summary>
        internal static string margharitaTitle {
            get {
                return ResourceManager.GetString("margharitaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podobno ten mentolowy koktajl ma już ponad 400 lat. Pochodzi z Kuby – nie bez powodu więc jego smak przywodzi na myśl pełne słońca plaże i szum Morza Karaibskiego. Legendy mówią, że mojito ewoluowało z napoju, którym raczyli się angielscy korsarze, w tym słynny kapitan Drake – rumu z trzciny cukrowej połączonego z cukrem i cytrusami. Inni historycy twierdzą z kolei, że czymś podobnym raczyli się kubańscy niewolnicy..
        /// </summary>
        internal static string mohitoDescription {
            get {
                return ResourceManager.GetString("mohitoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 ml białego rumu.
        /// </summary>
        internal static string mohitoIngredient1 {
            get {
                return ResourceManager.GetString("mohitoIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pół limonki + ćwiartka do dekoracji.
        /// </summary>
        internal static string mohitoIngredient2 {
            get {
                return ResourceManager.GetString("mohitoIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 łyżeczki cukru trzcinowego.
        /// </summary>
        internal static string mohitoIngredient3 {
            get {
                return ResourceManager.GetString("mohitoIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilka listków mięty.
        /// </summary>
        internal static string mohitoIngredient4 {
            get {
                return ResourceManager.GetString("mohitoIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 ml wody gazowanej.
        /// </summary>
        internal static string mohitoIngredient5 {
            get {
                return ResourceManager.GetString("mohitoIngredient5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limonkę wyszorować, pokroić na ćwiartki i wrzucić do szklanki typu long drink Zasypać cukrem i dokładnie ugnieść. Następnie dodać listki mięty i znowu ugnieść. Do połowy wysokości szklanki dodać lód, a następnie rum i znów lód. Zamieszać. Na wierzch dodać wodę gazowaną i delikatnie zmieszać. Szklankę udekorować limonką i listkami mięty..
        /// </summary>
        internal static string mohitoRecipe {
            get {
                return ResourceManager.GetString("mohitoRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mojito.
        /// </summary>
        internal static string mohitoTitle {
            get {
                return ResourceManager.GetString("mohitoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string moscowMuleDescription {
            get {
                return ResourceManager.GetString("moscowMuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml wódki.
        /// </summary>
        internal static string moscowMuleIngredient1 {
            get {
                return ResourceManager.GetString("moscowMuleIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 ml piwa imbirowego.
        /// </summary>
        internal static string moscowMuleIngredient2 {
            get {
                return ResourceManager.GetString("moscowMuleIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml soku z limonki.
        /// </summary>
        internal static string moscowMuleIngredient3 {
            get {
                return ResourceManager.GetString("moscowMuleIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szklankę typu long zasyp kruszonym lodem. Wlej wódkę i sok z limonki oraz wymieszaj. Na koniec uzupełnij piwem imbirowym oraz kruszonym lodem..
        /// </summary>
        internal static string moscowMuleRecipe {
            get {
                return ResourceManager.GetString("moscowMuleRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moscow Mule.
        /// </summary>
        internal static string moscowMuleTitle {
            get {
                return ResourceManager.GetString("moscowMuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jako że o Negronim po raz pierwszy usłyszano już w 1919 roku, drink ten niedawno obchodził swoje stulecie istnienia. A jak powstał? Legenda głosi, że pewnego dnia, pewnemu włoskiemu hrabiemu znudziło się spożywanie ciągle tego samego mocnego drinku alkoholowego (campari + czerwony wermut) i nakazał swojemu barmanowi, aby ten przygotował mu jakiś specjalny koktajl. Ów barman wyszedł z inicjatywą dodania do istniejącego już przepisu uncję ginu i tak powstał koktajl, który z czasem odziedziczył nazwę po słynny [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string negroniDescription {
            get {
                return ResourceManager.GetString("negroniDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 ml gin.
        /// </summary>
        internal static string negroniIngredient1 {
            get {
                return ResourceManager.GetString("negroniIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 ml Rosso Vermuth.
        /// </summary>
        internal static string negroniIngredient2 {
            get {
                return ResourceManager.GetString("negroniIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 ml Campari.
        /// </summary>
        internal static string negroniIngredient3 {
            get {
                return ResourceManager.GetString("negroniIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zest ze skórki pomarańczy.
        /// </summary>
        internal static string negroniIngredient4 {
            get {
                return ResourceManager.GetString("negroniIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gin, vermuth oraz Campari wlej do szklanicy pełnej lodu. Wymieszaj do czasu dobrego schłodzenia, następnie przelej zawartość do szklanki typu short pełnej lodu. Na koniec wyciśnij zest oraz wrzuć go do koktajlu..
        /// </summary>
        internal static string negroniRecipe {
            get {
                return ResourceManager.GetString("negroniRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negroni.
        /// </summary>
        internal static string negroniTitle {
            get {
                return ResourceManager.GetString("negroniTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string oldFashionedDescription {
            get {
                return ResourceManager.GetString("oldFashionedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml bourbon&apos;u.
        /// </summary>
        internal static string oldFashionedIngredient1 {
            get {
                return ResourceManager.GetString("oldFashionedIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 ml syropu cukrowego/ łyżka curku trzcinowego.
        /// </summary>
        internal static string oldFashionedIngredient2 {
            get {
                return ResourceManager.GetString("oldFashionedIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-3 krople Angostury.
        /// </summary>
        internal static string oldFashionedIngredient3 {
            get {
                return ResourceManager.GetString("oldFashionedIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zest ze skórki pomarańczy.
        /// </summary>
        internal static string oldFashionedIngredient4 {
            get {
                return ResourceManager.GetString("oldFashionedIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do szklanicy barmańskiej pełnej lodu wlej bourbon, cukier oraz Angosturę. Tak przygotowany koktajl mieszaj do czasu aż składniki się nie połączą w jednolity płyn. Przelej do szklanki typu short pełnej lodu, następnie zaromatyzuj zestem z pomarańczy..
        /// </summary>
        internal static string oldFashionedRecipe {
            get {
                return ResourceManager.GetString("oldFashionedRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Fashioned.
        /// </summary>
        internal static string oldFashionedTitle {
            get {
                return ResourceManager.GetString("oldFashionedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepis na napój, w którym dominuje kokosowa nuta, pochodzi z Karaibów, a dokładniej z Portoryko. Wyspa ta kusi rajskimi plażami i idealnymi warunkami do wypoczynku, a widok turystów sączących eleganckie drinki jest tu normą..
        /// </summary>
        internal static string pinaColadaDescription {
            get {
                return ResourceManager.GetString("pinaColadaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml białego rumu.
        /// </summary>
        internal static string pinaColadaIngredient1 {
            get {
                return ResourceManager.GetString("pinaColadaIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml mleczka kokosowego / syropu kokosowego / likieru kokosowego.
        /// </summary>
        internal static string pinaColadaIngredient2 {
            get {
                return ResourceManager.GetString("pinaColadaIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 ml soku ananasowego.
        /// </summary>
        internal static string pinaColadaIngredient3 {
            get {
                return ResourceManager.GetString("pinaColadaIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splash mleka.
        /// </summary>
        internal static string pinaColadaIngredient4 {
            get {
                return ResourceManager.GetString("pinaColadaIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do shakera wlej wszystkie składniki oraz energicznie wstrząśnij. Przelej zawartość do szklanki typu hurricane i gotowe..
        /// </summary>
        internal static string pinaColadaRecipe {
            get {
                return ResourceManager.GetString("pinaColadaRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pina Colada.
        /// </summary>
        internal static string pinaColadaTitle {
            get {
                return ResourceManager.GetString("pinaColadaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pornstar Martini drink, który zawdzięcza swoją popularność połączeniu wódki, soku z limonki i przecieru z marakui. Pamiętaj, że jeżeli nie posiadasz w domu musu z marakui użyj świeżego, soczystego miąższu z owocu marakui, który dodasz do drinka. Marakuja sprawia, że nasz drink jest niezwykle orzeźwiający i czuć w nim posmak kwasowości..
        /// </summary>
        internal static string pornStarMartiniDescription {
            get {
                return ResourceManager.GetString("pornStarMartiniDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 ml wódki waniliowej / 45 ml wódki i 15 ml syropu waniliowego.
        /// </summary>
        internal static string pornstarMartiniIngredient1 {
            get {
                return ResourceManager.GetString("pornstarMartiniIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 ml puree z marakui lub syrop.
        /// </summary>
        internal static string pornstarMartiniIngredient2 {
            get {
                return ResourceManager.GetString("pornstarMartiniIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml soku z limonki.
        /// </summary>
        internal static string pornstarMartiniIngredient3 {
            get {
                return ResourceManager.GetString("pornstarMartiniIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml passoa.
        /// </summary>
        internal static string pornstarMartiniIngredient4 {
            get {
                return ResourceManager.GetString("pornstarMartiniIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml champagne.
        /// </summary>
        internal static string pornstarMartiniIngredient5 {
            get {
                return ResourceManager.GetString("pornstarMartiniIngredient5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wszystkie składniki poza szampanem do shakera, wstrząśnij z lodem i przelej do kieliszka. Szampana podajemy osobno od drinka, w kieliszku do szotów. Ważnym jest, by poinformować konsumującego drinka, że obie jego części należy pić oddzielnie..
        /// </summary>
        internal static string pornstarMartiniRecipe {
            get {
                return ResourceManager.GetString("pornstarMartiniRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pornstar Martini.
        /// </summary>
        internal static string pornstarMartiniTitle {
            get {
                return ResourceManager.GetString("pornstarMartiniTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex on the Beach w samym USA jest tak popularnym drinkiem, że jego miłośnicy 4 października hucznie obchodzą rok rocznie jego święto, przy okazji obchodów National Vodka Day..
        /// </summary>
        internal static string sexOnTheBeachDescription {
            get {
                return ResourceManager.GetString("sexOnTheBeachDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml likieru brzoskwiniowego.
        /// </summary>
        internal static string sexOnTheBeachIngrecient2 {
            get {
                return ResourceManager.GetString("sexOnTheBeachIngrecient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml wódki.
        /// </summary>
        internal static string sexOnTheBeachIngredient1 {
            get {
                return ResourceManager.GetString("sexOnTheBeachIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 ml soku pomarańczowego.
        /// </summary>
        internal static string sexOnTheBeachIngredient3 {
            get {
                return ResourceManager.GetString("sexOnTheBeachIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top-up sokiem żurawinowym.
        /// </summary>
        internal static string sexOnTheBeachIngredient4 {
            get {
                return ResourceManager.GetString("sexOnTheBeachIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wódkę, likier oraz sok pomarańczowy wlej do szklanki typu hurricane lub long pełną lodu. Wymieszaj łyżką, następnie kilkoma dash&apos;ami wlej sok żurawinowy..
        /// </summary>
        internal static string sexOnTheBeachRecipe {
            get {
                return ResourceManager.GetString("sexOnTheBeachRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex On The Beach.
        /// </summary>
        internal static string sexOnTheBeachTitle {
            get {
                return ResourceManager.GetString("sexOnTheBeachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string whiskySourDescription {
            get {
                return ResourceManager.GetString("whiskySourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml whisky.
        /// </summary>
        internal static string whiskySourIngredient1 {
            get {
                return ResourceManager.GetString("whiskySourIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml soku z cytryny.
        /// </summary>
        internal static string whiskySourIngredient2 {
            get {
                return ResourceManager.GetString("whiskySourIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 ml syropu cukrowego.
        /// </summary>
        internal static string whiskySourIngredient3 {
            get {
                return ResourceManager.GetString("whiskySourIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to białko jaja .
        /// </summary>
        internal static string whiskySourIngredient4 {
            get {
                return ResourceManager.GetString("whiskySourIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-3 krople Angostury.
        /// </summary>
        internal static string whiskySourIngredient5 {
            get {
                return ResourceManager.GetString("whiskySourIngredient5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do pustego shakera wlej białko jaja i energicznie wstrząśnij przez około 10-15 sekund. Następnie zasyp shaker lodem i  dolej resztę składników po czym ponownie wstrząśnij zawartość. Tak przygotowany koktajl przelej do szklanki typu short wypełnionej kostkami lodu..
        /// </summary>
        internal static string whiskySourRecipe {
            get {
                return ResourceManager.GetString("whiskySourRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhiskySour.
        /// </summary>
        internal static string whiskySourTitle {
            get {
                return ResourceManager.GetString("whiskySourTitle", resourceCulture);
            }
        }
    }
}
