//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recipies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recipies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Recipies", typeof(Recipies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string cubaLibreDescription {
            get {
                return ResourceManager.GetString("cubaLibreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml białego rumu.
        /// </summary>
        internal static string cubaLibreIngredient1 {
            get {
                return ResourceManager.GetString("cubaLibreIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100-150 ml Coca-Cola.
        /// </summary>
        internal static string cubaLibreIngredient2 {
            get {
                return ResourceManager.GetString("cubaLibreIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 ćwiartki limonki.
        /// </summary>
        internal static string cubaLibreIngredient3 {
            get {
                return ResourceManager.GetString("cubaLibreIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do szklanki typu long wrzuć cząstki limonki, zgnieć mudlerem. Następnie zasyp szkło kostkami lodu, wlej rum i Coca-Colę..
        /// </summary>
        internal static string cubaLibreRecipe {
            get {
                return ResourceManager.GetString("cubaLibreRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba Libre.
        /// </summary>
        internal static string cubaLibreTitle {
            get {
                return ResourceManager.GetString("cubaLibreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink margarita pochodzi z Meksyku. Jego nazwa prawdopodobnie wzięła się od imienia kobiety, dla której został przygotowany po raz pierwszy. To pyszny, orzeźwiający napój najczęściej przygotowywany z dodatkiem cytryny. Można go również podawać z innymi owocami lub sokami owocowymi - szczególną popularnością cieszy się wersja truskawkowa. Ważnym elementem podania Margarity jest crustowanie brzegu szklanki, w której podaje się koktajl..
        /// </summary>
        internal static string margharitaDescription {
            get {
                return ResourceManager.GetString("margharitaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml tequili.
        /// </summary>
        internal static string margharitaIngredient1 {
            get {
                return ResourceManager.GetString("margharitaIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml triple sec.
        /// </summary>
        internal static string margharitaIngredient2 {
            get {
                return ResourceManager.GetString("margharitaIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sok z połówki limonki.
        /// </summary>
        internal static string margharitaIngredient3 {
            get {
                return ResourceManager.GetString("margharitaIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 ml syropu cukrowego.
        /// </summary>
        internal static string margharitaIngredient4 {
            get {
                return ResourceManager.GetString("margharitaIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do shakera wlewamy tequile, triple sec, sok z limonki, wrzucamy kostki lodu i shake-ujemy. Zawartość shakera wlewamy do kieliszka koktajlowego. Smacznego!.
        /// </summary>
        internal static string margharitaRecipe {
            get {
                return ResourceManager.GetString("margharitaRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margharita.
        /// </summary>
        internal static string margharitaTitle {
            get {
                return ResourceManager.GetString("margharitaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podobno ten mentolowy koktajl ma już ponad 400 lat. Pochodzi z Kuby – nie bez powodu więc jego smak przywodzi na myśl pełne słońca plaże i szum Morza Karaibskiego. Legendy mówią, że mojito ewoluowało z napoju, którym raczyli się angielscy korsarze, w tym słynny kapitan Drake – rumu z trzciny cukrowej połączonego z cukrem i cytrusami. Inni historycy twierdzą z kolei, że czymś podobnym raczyli się kubańscy niewolnicy..
        /// </summary>
        internal static string mohitoDescription {
            get {
                return ResourceManager.GetString("mohitoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 ml białego rumu.
        /// </summary>
        internal static string mohitoIngredient1 {
            get {
                return ResourceManager.GetString("mohitoIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pół limonki + ćwiartka do dekoracji.
        /// </summary>
        internal static string mohitoIngredient2 {
            get {
                return ResourceManager.GetString("mohitoIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 łyżeczki cukru trzcinowego.
        /// </summary>
        internal static string mohitoIngredient3 {
            get {
                return ResourceManager.GetString("mohitoIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilka listków mięty.
        /// </summary>
        internal static string mohitoIngredient4 {
            get {
                return ResourceManager.GetString("mohitoIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 ml wody gazowanej.
        /// </summary>
        internal static string mohitoIngredient5 {
            get {
                return ResourceManager.GetString("mohitoIngredient5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limonkę wyszorować, pokroić na ćwiartki i wrzucić do szklanki typu long drink Zasypać cukrem i dokładnie ugnieść. Następnie dodać listki mięty i znowu ugnieść. Do połowy wysokości szklanki dodać lód, a następnie rum i znów lód. Zamieszać. Na wierzch dodać wodę gazowaną i delikatnie zmieszać. Szklankę udekorować limonką i listkami mięty..
        /// </summary>
        internal static string mohitoRecipe {
            get {
                return ResourceManager.GetString("mohitoRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mojito.
        /// </summary>
        internal static string mohitoTitle {
            get {
                return ResourceManager.GetString("mohitoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepis na napój, w którym dominuje kokosowa nuta, pochodzi z Karaibów, a dokładniej z Portoryko. Wyspa ta kusi rajskimi plażami i idealnymi warunkami do wypoczynku, a widok turystów sączących eleganckie drinki jest tu normą..
        /// </summary>
        internal static string pinaColadaDescription {
            get {
                return ResourceManager.GetString("pinaColadaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 ml białego rumu.
        /// </summary>
        internal static string pinaColadaIngredient1 {
            get {
                return ResourceManager.GetString("pinaColadaIngredient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 ml mleczka kokosowego / syropu kokosowego / likieru kokosowego.
        /// </summary>
        internal static string pinaColadaIngredient2 {
            get {
                return ResourceManager.GetString("pinaColadaIngredient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 ml soku ananasowego.
        /// </summary>
        internal static string pinaColadaIngredient3 {
            get {
                return ResourceManager.GetString("pinaColadaIngredient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to splash mleka.
        /// </summary>
        internal static string pinaColadaIngredient4 {
            get {
                return ResourceManager.GetString("pinaColadaIngredient4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do shakera wlewamy wszystkie składniki, energicznie wstrząsamy. Przelewamy do szklanki typu hurricane i gotowe..
        /// </summary>
        internal static string pinaColadaRecipe {
            get {
                return ResourceManager.GetString("pinaColadaRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pina Colada.
        /// </summary>
        internal static string pinaColadaTitle {
            get {
                return ResourceManager.GetString("pinaColadaTitle", resourceCulture);
            }
        }
    }
}
